language: node_js
node_js:
  - "8.11.1"

# safelist
branches:
  only:
  - v2.0.0

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli@1.2.4

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng test --watch=false
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: